CATEGORIES = {
    "AI/ML": "ai",
    "JS": "javascript",
    "HTML": "html",
    "PHP": "php",
    "Ruby": "ruby",
    "Python": "python",
    "Java": "java",
    ".NET": "net",
    "Scala": "scala",
    "C": "c",
    "Mobile": "mobile",
    "Testing": "testing",
    "DevOps": "devops",
    "Admin": "admin",
    "Data": "data",
    "UX/UI": "ux",
    "PM": "pm",
    "Game": "gamedev",
    "Analytics": "analytics",
    "Security": "security",
    "Go": "go",
    "Support": "support",
    "ERP": "erp",
    "Architecture": "architecture",
    "Other": "other",
}